import os
import re
import textwrap

from ..config import settings
from ..models import Project, User
from .. import security
from .core import builder_agent, tester_agent


def _project_dir(project: Project) -> str:
    root = os.path.join(settings.workspace_root, f"project_{project.id}")
    os.makedirs(root, exist_ok=True)
    return root


async def build_product(user: User, project: Project, design: str) -> str:
    """Generate the product files into the workspace (saved to account, not deployed)."""
    html = await builder_agent(user, design)
    html = html.strip()
    if html.startswith("```"):
        html = re.sub(r"^```[a-zA-Z]*\n?", "", html)
        html = re.sub(r"\n?```$", "", html)
    if "<!DOCTYPE html>" not in html and "<html" not in html:
        html = "<!DOCTYPE html>\n" + html

    root = _project_dir(project)
    with open(os.path.join(root, "index.html"), "w", encoding="utf-8") as f:
        f.write(html)

    readme = f"# {project.title}\n\nGenerated by Product Factory.\n\nPrompt: {project.prompt}\n"
    with open(os.path.join(root, "README.md"), "w", encoding="utf-8") as f:
        f.write(readme)

    project.repo_path = root
    summary = f"Generated index.html ({len(html)} bytes) and README.md in {root}."
    test_checklist = await tester_agent(user, summary)
    return summary + "\n\n## QA Checklist\n" + test_checklist
